backend:
  name: github
  repo: colw/colwio
  branch: netlify-cms-support
media_folder: ""
collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Projects"
        name: "projects"
        file: "data/projects.yml"
        fields:
          - {label: "Title", name: "title", "widget": "string"}
          - {label: "Link", name: "link", "widget": "string"}
          - {label: "Image", name: "image", "widget": "string"}
          - {label: "Text", name: "text", "widget": "string"}
          - {label: "Year", name: "year", "widget": "string"}
      - label: "Skills"
        name: "skills"
        file: "data/skills.yml"
        fields:
          - {label: "Skill", name: "skill", "widget": "string"}
      - label: "Links"
        name: "links"
        file: "data/links.yml"
        fields:
          - {label: "Title", name: "title", "widget": "string"}
          - {label: "Link", name: "link", "widget": "string"}
          - {label: "Icon", name: "icon", "widget": "string"}
