backend:
  name: git-gateway
  branch: master

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "info"
    label: "Info"
    files:
      - file: "src/content/about.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}

      - file: "src/data/projects.yaml"
        label: "Projects"
        name: "projects"
        widget: "list"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Link", name: "link", widget: "string"}
          - {label: "Image", name: "image", widget: "string"}
          - {label: "Text", name: "text", widget: "string"}
          - {label: "Year", name: "year", widget: "string"}

      - file: "src/data/skills.yaml"
        label: "Skill Set"
        name: "skills"
        fields:
          - label: Skill
            name: skill
            widget: "list"
            field:
              label: "Skilltype"
              name: "skilltype"
              widget: "string"

      - file: "src/data/links.yaml"
        label: "Links"
        name: "links"
        widget: "list"
        fields:
          - label: "Link Item"
            name: "linkitem"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Link", name: "link", widget: "string"}
              - {label: "Icon", name: "icon", widget: "string"}
